### ISSUE TITLE
Chrome version

### ISSUE THREAD

**Issue by dnicolson** [danielpunkass/BugValet#1]
Now that macOS Mojave doesn't accept third-party extensions, porting this to Chrome seems like a logical next step.

**Comment by danielpunkass** [comment]
Hi @dnicolson - since I don't use Chrome, I'll probably end up packaging it in the form of a native Mac app whose sole purpose is to provide a Safari App Extension. If anybody else wants to create a Chrome adaptation I think it would be appropriate to host it here alongside the Safari extension.
